# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

before_install:
  - ls guideseq/guideseq.py
  - ls test/test_manifest_travis.yaml
  - ls test/test_manifest_step2_travis.yaml
  - cd test
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - git checkout tags/0.7.9a
  - make
  - cd ..
  - PATH=`pwd`/bwa:$PATH
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.25.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..
  - git clone https://github.com/samtools/samtools.git
  - cd samtools
  - git checkout tags/1.7
  - make
  - cd ..
  - PATH=`pwd`/samtools:$PATH
  - cd ..
  - git clone git://github.com/samtools/htslib.git
  - cd htslib
  - git checkout tags/1.7
  - cd ..
  - git clone git://github.com/samtools/bcftools.git
  - cd bcftools
  - git checkout tags/1.6
  - make
  - cd ..
  - PATH=`pwd`/bcftools:$PATH

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
    cd test && nosetests --exe -v
